# Page settings

baseurl = "http://example.org/"
languageCode = "en-us"
title = "John Doe Resume"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = "Pavel Kanyshev"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-6.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Gustavo Bramao"
        tagline = "Performance Marketing"
        avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: gustavobramao@live.fr"
        title = "gustavobramao@live.fr"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+34640807136"
        title = "+34640807136"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "https://medium.com/@gustavobramao"
        title = "medium@gus.com"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/gustavobramao"
        title = "linkedin/gustavobramao"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/gustavobramao"
        title = "github.com/gs_hack"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/gustavobramao"
        title = "@gs_science"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "Master in Digital Markteing"
        college = "University of San Jorge"
        dates = "2012 - 2014"

        [[params.education.list]]
        degree = "Bachelor in Economics & BA"
        college = "University Bordeaux IV"
        dates = "2007 - 2010"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "French"
        level = "Native"

        [[params.language.list]]
        language = "English"
        level = "Professional"

        [[params.language.list]]
        language = "Spanish"
        level = "Professional"

        [[params.language.list]]
        language = "Portuguese"
        level = "Professional"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Freeskiing"

        [[params.interests.list]]
        interest = "Wakeboarding"

        [[params.interests.list]]
        interest = "Digital Marketing"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "**Performance Marketing Manager** passionate about: Search, performance, attribution, data mining and incrementality measurement.With (+) 6 years experience in performance marketing, I’m managing multi-million/€ in  performance advertisement internationally, Full stack Growth Marketer strong user acquisition & retention competencies including: Search, Social, Display, Affiliates, Mobile and CRM. Currently driving projects focusing in performance marketing & data science -  Meaning that I’m actioning campaigns/data to drive highest iROI, mainly using machine learning regression techniques."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Head of Performance Marketing"
        dates = "2017 - Present"
        company = "Inditex, Barcelona"
        details = "Heading a Global Performance Marketing strategy & execution of the Paid/Organic channels for Bershka’s e-commerce - Optimizing performance with a test & learn approach and focusing in marketing science using MMM and MTA models."

        [[params.jobs.list]]
        position = "Marketing Project Manager"
        dates = "2016 - 2017"
        company = "Filovent, Barcelona"
        details = "Marketing project manager, mainly focused in optimizing search, product for SEO and mentoring for Paid. Teach to team best practices in performance marketing. Solved paid marketing tracking issues and automated dashboards using SQL & R."

        [[params.jobs.list]]
        position = "Head of Performance Marketing"
        dates = "2015 - 2016"
        company = "Blissbooker, Barcelona"
        details = "Managing an in house team of performance marketing specialist in order to hit the numbers, define tactics and hands-on execution accross SEO SEA Paid Social & Dispaly."

        [[params.jobs.list]]
        position = "Online Marketing Specialist"
        dates = "2013 - 2015"
        company = "Royal Caribbean International, Barcelona"
        details = "Planning acquistion and retention campaigns for the french market of RCI, experience working with agencies to optimizes tactics in order to maximise profit."

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "**Learning Curve** Creating predictve models using machine learning and regression with Causal Impact and Prohet in R - SEO scripting and Google analytics hits mining."

        [[params.projects.list]]
        title = "Github projects"
        url = "https://github.com/gustavobramao/data-sets/blob/master/GEO_Experiment"
        tagline = "Google Analytics API & Google Search console API using R - GEO Experiments, Marketing channel attribution, SEO scripting, CPAs Derivative, Causal impact and prohet forecasting."

        [[params.projects.list]]
        title = "Medium writting"
        url = "https://medium.com/@gustavobramao"
        tagline = "I write about my passion for performance & marketing science and share my learnings on experiments."

        [[params.projects.list]]
        title = "Vinyl Label Owner"
        url = "https://www.discogs.com/fr/label/959267-The-Game"
        tagline = "The Game Records founded with Love from Barcelona, 90's house flavored."


    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "SEA"
        level = "99%"
                
        [[params.skills.list]]
        skill = "Paid Social"
        level = "98%"

        [[params.skills.list]]
        skill = "SEO"
        level = "95%"

        [[params.skills.list]]
        skill = "MTA"
        level = "90%"

        [[params.skills.list]]
        skill = "Dispaly"
        level = "80%"

        [[params.skills.list]]
        skill = "MMM"
        level = "75%"

        [[params.skills.list]]
        skill = "R & SQL"
        level = "69%"


